# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import query_pb2 as query__pb2


class QueryServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHoneypots = channel.unary_unary(
                '/grpc.QueryServer/GetHoneypots',
                request_serializer=query__pb2.Empty.SerializeToString,
                response_deserializer=query__pb2.Honeypots.FromString,
                )
        self.NewHoneypot = channel.unary_unary(
                '/grpc.QueryServer/NewHoneypot',
                request_serializer=query__pb2.StartHoneypot.SerializeToString,
                response_deserializer=query__pb2.ReturnCode.FromString,
                )


class QueryServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetHoneypots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewHoneypot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHoneypots': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHoneypots,
                    request_deserializer=query__pb2.Empty.FromString,
                    response_serializer=query__pb2.Honeypots.SerializeToString,
            ),
            'NewHoneypot': grpc.unary_unary_rpc_method_handler(
                    servicer.NewHoneypot,
                    request_deserializer=query__pb2.StartHoneypot.FromString,
                    response_serializer=query__pb2.ReturnCode.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.QueryServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class QueryServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHoneypots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.QueryServer/GetHoneypots',
            query__pb2.Empty.SerializeToString,
            query__pb2.Honeypots.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NewHoneypot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.QueryServer/NewHoneypot',
            query__pb2.StartHoneypot.SerializeToString,
            query__pb2.ReturnCode.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class HoneypotManagementServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatStream = channel.unary_stream(
                '/grpc.HoneypotManagementServer/ChatStream',
                request_serializer=query__pb2.Empty.SerializeToString,
                response_deserializer=query__pb2.Event.FromString,
                )
        self.SendEvent = channel.unary_unary(
                '/grpc.HoneypotManagementServer/SendEvent',
                request_serializer=query__pb2.Event.SerializeToString,
                response_deserializer=query__pb2.Empty.FromString,
                )


class HoneypotManagementServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ChatStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HoneypotManagementServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=query__pb2.Empty.FromString,
                    response_serializer=query__pb2.Event.SerializeToString,
            ),
            'SendEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.SendEvent,
                    request_deserializer=query__pb2.Event.FromString,
                    response_serializer=query__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.HoneypotManagementServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HoneypotManagementServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ChatStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.HoneypotManagementServer/ChatStream',
            query__pb2.Empty.SerializeToString,
            query__pb2.Event.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.HoneypotManagementServer/SendEvent',
            query__pb2.Event.SerializeToString,
            query__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
